swagger: '2.0'
info:
  title: Gateway Console
  version: v3
consumes:
  - application/json
paths: 
  /v3/devices/{id}/console:
    get:
      operationId: "establishGatewayDeviceConsoleSession"
      summary: "Establish a console session"
      description: |
        This WebSocket-based API establishes a console session with a gateway device.
        <br>
        Use this endpoint to establish a WebSocket connection to the device console. Once the connection is in place, you can use the protocol below to exchange messages related to the console session.
        You must provide the api key as bearer token to authenticate the request.
        All messages sent between the server and the client are contained inside a message envelope. The envelope contains a type field describing what format the payload is in and how to interpret the message:
        
        ```json
        {
          "type": [string],
          "payload": [any],
          "sessionID": [string]
        }
        ```
        <br>
        ## Message types and payload formats
        
        | Message Type  | Payload Format   | Description |
        |:------------- |:------------- |:------------- |
        | **resize** | `ResizePayload` | Can be sent by the client to the server to notify the device that the console window size has changed. |
        | **input** | `string` | Sent from the client to the server when keyboard input is provided to the console. stdin |
        | **output** | `string` | Sent from the server to the client when console output is produced. stdout + stderr |
        
        ### `ResizePayload`
        ```json
        {
          "width": [integer], // number of columns
          "height": [integer] // number of rows
        }
        ```
        | Field Name  | Format   | Description |
        |:------------- |:------------- |:------------- |
        | width | integer | The width of the console window in columns. |
        | height | integer | The height of the console window in rows. |
        <br>
        
        ## Protocol Sequence Diagram

        The diagram shows how messages are passed between the client and the server after initiating a console session:
        ```
        Client                    Pelion Cloud (/v3/devices/{id}/console)                      Device
          |                                           |                                           |
          |                                           |                                           |
          |-----------------[Input]------------------>|                                           |
          |                                           |-----------------[Input]------------------>|
          |                                           |<----------------[Output]------------------|
          |<----------------[Output]------------------|                                           |
          |-----------------[Input]------------------>|                                           |
          |                                           |-----------------[Input]------------------>|
          |                                           |<----------------[Output]------------------|
          |<----------------[Output]------------------|                                           |
          |                                           |                                           |
          |-----------------[Resize]----------------->|                                           |
          |                                           |-----------------[Resize]----------------->|
          |                                           |                                           |
          |                                           |<----------------[Output]------------------|
          |<----------------[Output]------------------|                                           |
          |                                           |                                           |
          |                                           |                                           |
          |                                           |                                           |
        
        Input is always forwarded from the client to the console session on the relevant device to be passed to the stdin stream. The client does not need to provide a session ID for input messages.
        Ouptut is forwarded from the device console session's stdout and stderr streams to the client.
        Resize messages are forwarded from the client to the console session on the device.
        ```
        <br>
        If the console session is terminated by the device disconnecting, the WebSocket connection is closed.
        <br>
        All communication is text-based.
        <br>
        ## Errors and Close Codes
        - If you send binary data instead of text data over the websocket connection, the socket closes with code 1003.
        - If you send text data that is not valid JSON, the socket closes with code 1002 and error message 'Data could not be parsed as JSON'.
        - If you send text data that is valid JSON but does not follow a valid message schema, the socket closes with code 1002 and error message 'Object format invalid'.
        - If you try to establish a console session with a device that is not prepared for console, the socket closes with code 1011 and error message 'The device console is not working'.
        - If your client fails to respond to ping messages from the server with a matching pong message, the server disconnects the client, assuming the connection has timed out.
      tags:
        - Gateway Terminal Public API
      parameters:
      - name: id
        in: path
        type: string
        required: true
        description: The id of the device
      - name: Connection
        in: header
        type: string
        default: Upgrade
        required: true
        description: The websocket connection header. Must be 'Upgrade'.
      - name: Upgrade
        in: header
        type: string
        default: websocket
        required: true
        description: The protocol upgrade header. Must be 'websocket'.
      - name: Sec-WebSocket-Protocol
        in: header
        type: string
        required: false
        description: |-
          Access key or user token must be present in the `Sec-WebSocket-Protocol` header **if Authorization header cannot be provided**: `Sec-WebSocket-Protocol:wss,pelion_ak_{access_key}`.
      - name: Origin
        in: header
        type: string
        required: false
        description: Originating host of the request.
      - name: Sec-WebSocket-Version
        in: header
        type: integer
        required: true
        description: WebSocket version. Must be 13.
        default: 13
      - name: Sec-WebSocket-Key
        in: header
        type: string
        format: byte
        required: true
        description: |-
          The value of this header field must be a nonce consisting of a randomly selected 16-byte value that has been base64-encoded (see Section 4 of [RFC4648]). The nonce must be selected randomly for each connection.
      responses:
        '101':
          description: Connection established.
          headers:
            Upgrade:
              description: Always 'websocket' in accordance with the WebSocket specification.
              type: string
        '400':
          description: Bad request.
          schema:
            $ref: '../../api-common-definitions/standard.yaml#/definitions/ErrorResponse'
        '401':
          description: Not authenticated.
          schema:
            $ref: '../../api-common-definitions/standard.yaml#/definitions/ErrorResponse'
        '403':
          description: Access denied.
          schema:
            $ref: '../../api-common-definitions/standard.yaml#/definitions/ErrorResponse'
        '404':
          description: Not found.
          schema:
            $ref: '../../api-common-definitions/standard.yaml#/definitions/ErrorResponse'
        '500':
          description: Internal server error.
          schema:
            $ref: '../../api-common-definitions/standard.yaml#/definitions/ErrorResponse'
