swagger: "2.0"
x-aliases:
  groups_field: &groups_field
    groups:
      description: An array containing an ID of each group this device belongs to.
      type: array
      items:
        type: string
        example: "00000000000000000000000000000000"
  issuer_fingerprint: &issuer_fingerprint
    issuer_fingerprint:
      type: string
      pattern: "[A-Fa-f0-9]{64}"
      x-nullable: true
      description: SHA256 fingerprint of the certificate used to validate the signature of the device certificate.
      example: "C42EDEFC75871E4CE2146FCDA67D03DDA05CC26FDF93B17B55F42C1EADFDC322"
  device_execution_mode: &device_execution_mode
        device_execution_mode:
          enum:
            - 0
            - 1
            - 5
          type: integer
          description: |-
            The execution mode from the certificate of the device. Defaults to inheriting from host_gateway device.
            Permitted values:
              - 0 - Unspecified execution mode (default if host_gateway invalid or not set). The device firmware uses a certificate that is not identified as a developer or production certificate.
              - 1 - Development device. The device firmware uses a developer certificate to communicate with Device Management.
              - 5 - Production device. The device firmware uses a factory-generated certificate to communicate with Device Management.
          example: 0
          default: 0
definitions:
    DeviceData:
      properties:
        operator_suspended:
          type: boolean
          description: Device has been suspended by operator.
        last_operator_suspended_category:
          type: string
          description: The reference of the block category.
          pattern: "[a-f0-9_]{32}"
          example: "maintenance"
        last_operator_suspended_description:
          type: string
          maxLength: 2000
          description: The most recent description why the device was suspended or returned to service.
          example: Suspended for maintenance.
        last_operator_suspended_updated_at:
          type: string
          format: date-time
          description: The timestamp of the most recent suspension activity.
          example: "2017-05-22T12:37:55.576563Z"
        system_suspended:
          type: boolean
          description: Is the device suspended by the system?
        last_system_suspended_category:
          type: string
          description: The reference of the block category.
          pattern: "[a-f0-9_]{32}"
          example: "maintenance"
        last_system_suspended_description:
          type: string
          maxLength: 2000
          description: The most recent description of why the device was blocked or unblocked by the system.
          example: A certificate in the device's certificate chain was blacklisted by the system.
        last_system_suspended_updated_at:
          type: string
          format: date-time
          description: The timestamp of the most recent system block activity.
          example: "2017-05-22T12:37:55.576563Z"
        lifecycle_status:
          type: string
          enum:
          - enabled
          - blocked
          description: |-
            The lifecycle status of the device.
            * Enabled: The device is allowed to connect to Pelion Device Management.
            * Blocked: The device is prevented from connecting to Pelion Device Management. Device can be, for example, 'suspended'.
          example: enabled
        account_id:
          type: string
          description: The ID of the associated account.
          example: "00000000000000000000000000000000"
        <<: *device_execution_mode
        auto_update:
          type: boolean
          description: "DEPRECATED: Mark this device for automatic firmware update."
        bootstrap_expiration_date:
          format: date
          type: string
          x-nullable: true
          description: The expiration date of the certificate used to connect to bootstrap server.
        bootstrapped_timestamp:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The timestamp of the device's most recent bootstrap process.
        ca_id:
          type: string
          maxLength: 500
          description: The certificate issuer's ID.
          example: "00000000000000000000000000000000"
        component_attributes:
          type: object
          maxProperties: 10
          additionalProperties:
            type: string
            maxLength: 128
          description: Up to ten custom key-value attributes. Note that keys cannot begin with a number. Both keys and values are limited to 128 characters. Updating this field replaces existing contents.
          example:
            key: value
        connector_expiration_date:
          format: date
          type: string
          x-nullable: true
          description: The expiration date of the certificate used to connect to LwM2M server.
        created_at:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The timestamp of when the device was created in the device directory.
        custom_attributes:
          type: object
          maxProperties: 5
          additionalProperties:
            type: string
            maxLength: 128
            pattern: "^[A-Za-z].*"
          description: Up to five custom key-value attributes. Note that keys cannot begin with a number. Both keys and values are limited to 128 characters. Updating this field replaces existing contents.
          example:
            key: value
        deployed_state:
          enum:
            - development
            - production
          type: string
          description: "DEPRECATED: The state of the device's deployment."
        deployment:
          type: string
          description: "DEPRECATED: The last deployment used on the device."
          example: ""
        description:
          type: string
          maxLength: 2000
          description: The description of the device.
          example: "Temperature measuring device"
        device_class:
          type: string
          maxLength: 32
          description: An ID representing the model and hardware revision of the device.
          example: ""
        id:
          type: string
          description: The ID of the device. The device ID is used across all Device Management APIs.
          example: "00000000000000000000000000000000"
        device_key:
          type: string
          maxLength: 512
          description: The fingerprint of the device certificate.
          example: "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
        endpoint_name:
          type: string
          description: The endpoint name given to the device. The endpoint_name is from the device certificate and is set by factory tool.
          example: "00000000-0000-0000-0000-000000000000"
          readOnly: true
        endpoint_type:
          type: string
          description: The endpoint type of the device. For example, the device is a gateway.
          maxLength: 64
          example: ""
        etag:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The entity instance signature.
        firmware_checksum:
          type: string
          description: The SHA256 checksum of the current firmware image.
          example: "0000000000000000000000000000000000000000000000000000000000000000"
        host_gateway:
          type: string
          description: The ID of the host gateway, if appropriate. A device behind Edge has this host_gateway set.
          example: ""
        manifest:
          type: string
          description: "DEPRECATED: The URL for the current device manifest."
          example: ""
        manifest_timestamp:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The timestamp of the current manifest version.
        mechanism:
          enum:
            - connector
            - direct
          type: string
          description: 'NOT USED: The ID of the channel used to communicate with the device.'
        mechanism_url:
          type: string
          description: 'NOT USED: The address of the connector to use.'
          example: ""
        name:
          type: string
          maxLength: 128
          description: The name given by the web application for the device. Device itself provides only the endpoint_name.
          example: "00000000-0000-0000-0000-000000000000"
        object:
          type: string
          description: The API resource entity.
          example: "device"
        serial_number:
          type: string
          description: The [serial number](https://www.pelion.com/docs/device-management-provision/latest/provisioning-info/lwm2m-device-object.html#serial-number) of the device. The serial number is injected by the factory tool during manufacturing.
          example: "00000000-0000-0000-0000-000000000000"
        state:
          enum:
            - unenrolled
            - cloud_enrolling
            - bootstrapped
            - registered
            - deregistered
          type: string
          description: |-
            The current state of the device.
            * Unenrolled: The device has been created, but has not yet bootstrapped or connected to Device Management.
            * Cloud_enrolling: The device is bootstrapping for the first time. This state is set only while bootstrapping is in progress. For example, an external CA gives an error, and the device tries to bootstrap again after few seconds.
            * Bootstrapped: The device has bootstrapped, and has credentials to connect to Device Management.
            * Registered: The device has registered with Pelion Device Management. [Device commands](https://www.pelion.com/docs/device-management-api/connect/) can be queued. The device sends events for [subscribed](https://www.pelion.com/docs/device-management/current/resources/handle-resource-webapp.html) resources.
            * Deregistered: The device has requested deregistration, or its registration has expired.
        updated_at:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The time this data object was updated.
        vendor_id:
          type: string
          description: The device vendor ID.
          example: "00000000-0000-0000-0000-000000000000"
        enrolment_list_timestamp:
          format: date-time
          example: "2017-05-22T12:37:55.576563Z"
          type: string
          description: The claim date/time.
        <<: *groups_field
        <<: *issuer_fingerprint

    DeviceDataPostRequest:
      properties:
        <<: *device_execution_mode
        auto_update:
          type: boolean
          description: "DEPRECATED: Mark this device for automatic firmware update."
        bootstrap_expiration_date:
          x-nullable: true
          format: date
          example: "2017-05-22"
          type: string
          description: The expiration date of the certificate used to connect to bootstrap server.
        ca_id:
          type: string
          maxLength: 500
          description: The certificate issuer's ID.
          example: "00000000000000000000000000000000"
        connector_expiration_date:
          x-nullable: true
          format: date
          example: "2017-05-22"
          type: string
          description: The expiration date of the certificate used to connect to the LwM2M server.
        custom_attributes:
          type: object
          maxProperties: 5
          additionalProperties:
            type: string
            maxLength: 128
            pattern: "^[A-Za-z].*"
          description: Up to five custom key-value attributes. Note that keys cannot begin with a number. Both keys and values are limited to 128 characters. Updating this field replaces existing contents.
          example:
            key: value
        deployment:
          type: string
          description: "DEPRECATED: The last deployment used on the device."
          example: ""
        description:
          type: string
          maxLength: 2000
          description: The description of the device.
          example: ""
        device_class:
          type: string
          maxLength: 32
          description: An ID representing the model and hardware revision of the device.
        device_key:
          type: string
          maxLength: 512
          description: The fingerprint of the device certificate.
          example: "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
        endpoint_name:
          type: string
          maxLength: 64
          description: The endpoint name given to the device.
          example: "00000000-0000-0000-0000-000000000000"
        endpoint_type:
          type: string
          description: The endpoint type of the device. For example, the device is a gateway.
          maxLength: 64
          example: ""
        host_gateway:
          type: string
          description: The ID of the host gateway, if appropriate.
          example: ""
        manifest:
          type: string
          description: "DEPRECATED: The URL for the current device manifest."
          example: ""
        mechanism:
          enum:
          - connector
          - direct
          type: string
          description: The ID of the channel used to communicate with the device.
        mechanism_url:
          type: string
          description: The address of the connector to use.
          example: ""
        name:
          type: string
          maxLength: 128
          description: The name of the device.
          example: "00000000-0000-0000-0000-000000000000"
        serial_number:
          type: string
          maxLength: 64
          description: The serial number of the device.
          example: "00000000-0000-0000-0000-000000000000"
        state:
          enum:
          - unenrolled
          - cloud_enrolling
          - bootstrapped
          - registered
          - deregistered
          type: string
          description: The current state of the device.
        vendor_id:
          type: string
          maxLength: 255
          description: The device vendor ID.
          example: "00000000-0000-0000-0000-000000000000"
        <<: *issuer_fingerprint

    DeviceDataPutRequest:
      properties:
        auto_update:
          type: boolean
          description: "DEPRECATED: Mark this device for automatic firmware update."
        ca_id:
          type: string
          maxLength: 500
          description: "The certificate issuer's ID. WARNING: This value comes from the device, and should not be changed via the API."
          example: "00000000000000000000000000000000"
        custom_attributes:
          type: object
          maxProperties: 5
          additionalProperties:
            type: string
            maxLength: 128
            pattern: "^[A-Za-z].*"
          description: Up to five custom key-value attributes. Note that keys cannot begin with a number. Both keys and values are limited to 128 characters. Updating this field replaces existing contents.
          example:
            key: value
        description:
          type: string
          maxLength: 2000
          description: The description of the device.
          example: ""
        device_key:
          type: string
          maxLength: 512
          description: "The fingerprint of the device certificate. WARNING: This value comes from the device, and should not be changed via the API."
          example: "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
        endpoint_name:
          type: string
          maxLength: 64
          description: "The endpoint name given to the device. WARNING: This value comes from the device, and should not be changed via the API."
          example: "00000000-0000-0000-0000-000000000000"
          readOnly: true
        endpoint_type:
          type: string
          description: The endpoint type of the device. For example, the device is a gateway.
          maxLength: 64
          example: ""
        host_gateway:
          type: string
          description: The ID of the host gateway, if appropriate.
          example: ""
        name:
          type: string
          maxLength: 128
          description: The name of the device.
          example: "00000000-0000-0000-0000-000000000000"

    DevicePage:
      properties:
          data:
            items:
              $ref: '#/definitions/DeviceData'
            type: array
          after:
            type: string
            description: An offset token for current page.
            example: '01631667477600000000000100100374'
          has_more:
            type: boolean
            description: Are there more results available.
            example: false
          limit:
            type: integer
            description: How many objects to retrieve in the page. The minimum limit is 2 and the maximum is 1000. Limit values outside of this range are set to the closest limit.
            example: 50
            minimum: 2
            maximum: 1000
          object:
            type: string
            description: The type of this API object is a "list".
            example: "list"
          order:
            type: string
            description: The order of the records based on creation time, `ASC` or `DESC`; by default `ASC`.
            example: "DESC"
          total_count:
            format: integer
            type: integer
            example: 1
